services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: business-ops-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Preserve node_modules in container
      - /app/.next # Preserve .next folder in container
    environment:
      - NODE_ENV=development
      # For Docker, we need to use the API service name and port
      # Make sure this matches exactly what the backend is exposing
      - NEXT_PUBLIC_API_URL=http://app:5555/api/v1
    working_dir: /app
    command: npm run dev